# Site
title:              3rd Strike Chile
bio:                'Bienvenido a la comunidad Chilena de jugadores de<br>Street Fighter III: 3rd Strike'
description:        "Comunidad Chilena de jugadores de Street Fighter III: 3rd Strike"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://127.0.0.1:4000
404-img:            'assets/img/404.png'

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics: UA-144171183-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            3rdstrikecl
facebook:           groups/3rdstrikecl
#github-url:         username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          IGusername
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam-id:           userid
steam-group:        3rdstrikecl
#dribbble:          username
#youtube:           YTuser
youtube-channel:   UCJ1xtgAxWu1_QmU4y44VeBQ
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
